build:
  environment:
    python: "pypy3.7-7.3.4"  # Use PyPy 3.7 (7.3.4)
  dependencies:
    before:
      - python3 -m ensurepip  # Ensure pip is installed for PyPy
      - python3 -m pip instal
      - cd 11
      
             # Install GCC for compiling C programs
     # Compile the C program
  tests:
    override:
     
      - python3 m.py 
      - python3 m.py 
      - python3 m.py 
      - python3 m.py 
      - python3 m.py 
      - python3 m.py 
      - python3 m.py 
